---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  tasks:
  - name: Gather package facts
    package_facts:
      manager: auto

  - name: Verify Packages
    assert:
      that: "'{{ item }}' in ansible_facts.packages"
    with_items:
      - nginx
      - php7.2
      - php7.2-fpm
